name: RedClocktower
version: '0.5.1'
main: io.github.aktomik.redclocktower.RedClocktower
api-version: '1.21'
#commands:
# brigader commands are not handled here

permissions:
  redclocktower.player:
    description: Storyteller permission
    default: op
  redclocktower.storyteller:
    description: Storyteller permission
    default: op