name: RedClocktower
version: '0.7.3'
main: io.github.aktomik.redclocktower.RedClocktower
api-version: '1.21'
#commands:
# we are using brigader commands

permissions:
  redclocktower.player:
    description: Player permission
    default: true
  redclocktower.storyteller:
    description: Storyteller permission
    default: op